### PR TITLE
Added a cool installer uninstaller for windows, linux and maxos

### PR DESCRIPTION
**Pull request by ParisNeo**
Hi, I have added few scripts to install/uninstall every thing in a completely automated manner

### CODE REVIEW

**Comment by abdeladim-s** [comment]
Thanks a lot @ParisNeo for providing the installers. 
I will test them asap.

**Comment by ParisNeo** [comment]
I have generated the LLAMA image using Stable diffusion then cnverted it to ASCII art.
I think it is a good idea to have such artworks in the installer :).
Don't hesitate to test it.
Thank you.

**Comment by abdeladim-s** [comment]
@ParisNeo, The linux installer looks good, I don't have access to others OSs so i didn't test the other installers though.
could you please add a few words to the readme on how to use them, so I can merge the PR. 
Thanks!

**Review by abdeladim-s — APPROVED** [review]
Approved

**Pull request merged**
